### ISSUE TITLE
Improve clinical trial curation tool based on CTML from MatchMiner

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/GSoC#103]
Over the past couple month, the collaborators from University Health Network(UHN), Princess Margaret have notified us that they are working on a new curation platform [Clinical Trial Integrated Matching System (CTIMS)](https://github.com/pughlab/ctims) and is in beta phase for testing. 

The tool is crafted using the [CTML ](https://matchminer.org/#ctml) format and is supposed to work with all existing YAML/JSON trial data.

To strengthen the collaboration and also avoid unnecessary engineering, we decided to further improve the tool so it can be better adopted within other institutions that would intend to use MatchMiner for clinical trial matching.

The Google of Summer Code project therefore is updated based on the context above.

**Goal:**
Add/update features of CTIMS to improve the product and increase the adoption rate.

**TODO List:**
- [ ] Setup CTIMS locally and get familiar with the tech stack
- [ ] Basic Integration of API [clinicaltrials.gov](http://clinicaltrials.gov/). [RFC is HERE](https://docs.google.com/document/d/1qSfX-c-0Kb1GKAP0aVeonry1guT-vru41EXvCum8myU/edit)
- [ ] Validate cancer type based on OncoTree

**Comment by ahmad-04** [comment]
Hey is this project open to work on??

**Comment by zhx828** [comment]
> Hey is this project open to work on??

No at this moment unfortunately

**Comment by Prathiksha-jain** [comment]
Subject: Expression of Interest in Contributing to Your Project
I hope this message finds you well. I have been following your project closely and am genuinely excited about the work you're doing. I am eager to contribute my skills, explore the project further, and learn in the process.

I kindly request the opportunity to collaborate and work on this project. I believe that my experience and enthusiasm can be valuable assets to your team.

Please let me know if there is an opportunity for me to get involved.

Thank you.

**Comment by Shashank2104125** [comment]
@zhx828 will this project open for GSoC 2024?
